#!/usr/bin/env ruby
#LIB_PATH = "#{ENV['HOME']}/work/myruby/markdown2html/"
$LOAD_PATH.push('/home/iguto/work/myruby/markdown2html')
$LOAD_PATH.push('/home/masahiro/work/ruby_prod/markdown2html.git')

require 'markdown2html'

parse_extensions = {
  :no_intra_emphasis => true,
  :tables => true,
  :fenced_code_blocks => true,
  :autolink => true
}

render_extensinos = {
  :hard_wrap => true,
	:with_toc_data => true
}

#STDOUT.write Redcarpet::Markdown.new(HTMLwithPygments.new(render_extensinos),

render = HTMLwithPygments.new()#render_extensinos)
#puts Redcarpet::Markdown.new(render, parse_extensions).render(ARGF.read)
html_toc = Redcarpet::Markdown.new(Redcarpet::Render::HTML_TOC)
markdown = Redcarpet::Markdown.new(render, parse_extensions)
md_file = ARGF.read.delete('[TOC]')
puts html_toc.render(md_file)
puts markdown.render(md_file)
#puts Redcarpet::Markdown.new(render, parse_extensions).render(ARGF.read)
